name: remote ssh command
on: [push]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }} 
        script: |
          cp .env ~/faceid-ecommerce/backend
          cd ~/faceid-ecommerce
          git pull origin master
          git status 
          npm --prefix ./client run build
          echo "Build complete"
          pm2 restart all