name: remote ssh command
on: [push]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }} 
        script: |
          cd ~/faceid-ecommerce
          git pull origin master
          git status
          npm run init
          npm run start:backend
          npm run start:client